version: "3.8"

services:
  springboot-app:
    build:
      context: .
    container_name: backend.chat.dvai
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db.chat.dvai
    restart: always
    environment:
      POSTGRES_USER: dvai-main-agent
      POSTGRES_PASSWORD: NLcep2gjJO809QL9fqnplVU3Ymuuzw9w6WCYCtQw1Sr
      POSTGRES_DB: dvai
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
